sample 10x_1 and 10x_4 are healthy individual
```{r}
raw_1 <- readMM("~/storage/Others/Tcf21/Liver_Dobie/GSM4085623_10x_1_matrix.mtx.gz")
raw_4 <- readMM("~/storage/Others/Tcf21/Liver_Dobie/GSM4085626_10x_4_matrix.mtx.gz")
raw_1.gene <- read.table("~/storage/Others/Tcf21/Liver_Dobie/GSM4085623_10x_1_genes.tsv.gz",header = FALSE, stringsAsFactors = FALSE)
raw_1.barcode <- read.table("~/storage/Others/Tcf21/Liver_Dobie/GSM4085623_10x_1_barcodes.tsv.gz", header = FALSE, stringsAsFactors = FALSE)
raw_4.gene <- read.table("~/storage/Others/Tcf21/Liver_Dobie/GSM4085626_10x_4_genes.tsv.gz",header = FALSE, stringsAsFactors = FALSE)
raw_4.barcode <- read.table("~/storage/Others/Tcf21/Liver_Dobie/GSM4085626_10x_4_barcodes.tsv.gz", header = FALSE, stringsAsFactors = FALSE)
```

unique genes
```{r}
sum(raw_1.gene$V2!=raw_4.gene$V2) # two lists of genes are the same
genes.dup <- names(which(table(raw_1.gene$V2) >=2))
genes.unique <- raw_1.gene$V2[!raw_1.gene$V2 %in% genes.dup]
```


```{r}
liver.dobie.1 <- as.data.frame(as.matrix(raw_1))[!raw_1.gene$V2 %in% genes.dup,]
rownames(liver.dobie.1) <- genes.unique
colnames(liver.dobie.1) <- paste0("HSC_",raw_1.barcode$V1)

liver.dobie.4 <- as.data.frame(as.matrix(raw_4))[!raw_1.gene$V2 %in% genes.dup,]
rownames(liver.dobie.4) <- genes.unique
colnames(liver.dobie.4) <- paste0("PF_",raw_4.barcode$V1)
```

```{r}
liver.dobie <- cbind(liver.dobie.1, liver.dobie.4)
saveRDS(liver.dobie, file = "~/storage/Others/Tcf21/liver.dobie.rds")
liver.dobie <- readRDS("~/storage/Others/Tcf21/liver.dobie.rds")
```

```{r}
cells.genes <- apply(liver.dobie,2,function(x) sum(x>0))
summary(cells.genes)
```

```{r}
dge.liver.dobie <- CreateSeuratObject(raw.data = liver.dobie)
dge.liver.dobie <- NormalizeData(object = dge.liver.dobie, normalization.method = "LogNormalize", 
    scale.factor = 10000)

dge.liver.dobie <- FindVariableGenes(object = dge.liver.dobie,mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, y.cutoff = 1, x.high.cutoff = 3)
dge.liver.dobie <- ScaleData(object = dge.liver.dobie)
dge.liver.dobie <- RunPCA(object = dge.liver.dobie, pc.genes = dge.liver.dobie@var.genes)
```

```{r fig.width=6,fig.height=4.5}
PCAPlot(object = dge.liver.dobie, dim.1 = 1, dim.2 = 2)
PCAPlot(object = dge.liver.dobie, dim.1 = 1, dim.2 = 3)
PCElbowPlot(object = dge.liver.dobie)
```


```{r fig.width=6,fig.height=4.5}
dge.liver.dobie <- RunTSNE(object = dge.liver.dobie, dims.use = 1:5)
TSNEPlot(object = dge.liver.dobie)
```

```{r fig.width=6,fig.height=4.5}
#dge.liver.dobie <- FindClusters(object = dge.liver.dobie, reduction.type = "pca", dims.use = 1:5, save.SNN = TRUE, resolution = 0.1)
DimPlot(object = dge.liver.dobie, reduction = "tsne", group.by = "res.0.1",do.label = TRUE)
```

```{r fig.width=10, fig.height=10}
FeaturePlot(dge.liver.dobie, features.plot = c("Tagln","Acta2","Tpm2","Gsn","Clec3b","Dpt","Ecm1","Vipr1","Colec11"), reduction.use = "tsne",nCol = 3,pch.use = 0.1)
```

```{r}
saveRDS(dge.liver.dobie, file = "~/storage/Others/Tcf21/Liver_Dobie/dge.liver.dobie.rds")
dge.liver.dobie <- readRDS("~/storage/Others/Tcf21/Liver_Dobie/dge.liver.dobie.rds")
```


0: HSC
1: FB
2: VSMC
```{r}
dge.liver.dobie@meta.data$celltypes <- plyr::mapvalues(dge.liver.dobie@meta.data$res.0.1, from = c(0:2), to = c("HSC","FB","VSMC"))
```

```{r}
liver.dobie.norm <- apply(dge.liver.dobie@raw.data,2,function(x) x/sum(x)*1e4)
```

```{r}
cell.types <- unique(dge.liver.dobie@meta.data$celltypes)
dge.liver.dobie.cen <- c()
for(i in cell.types){
  cells <- dge.liver.dobie@cell.names[dge.liver.dobie@meta.data$celltypes==i]
  cen <- apply(liver.dobie.norm[,cells],1,mean)
  dge.liver.dobie.cen <- cbind(dge.liver.dobie.cen, cen)
}
colnames(dge.liver.dobie.cen) <- cell.types
```

```{r}
mou.cen <- read.table("~/storage/HumanMacaqueMouseCompAnaysis/ligandReceptor/MouseAdultST25_7SomaticCellTypes_Centroids_Qianyi.txt",header = TRUE, row.names = 1)
colnames(mou.cen) <- c("InnateLymphoid","Macrophage","Endothelial", "Myoid", "Leydig","Sertoli","Tcf21+")
mou.markers <- read.table("~/storage/Others/Tcf21/MouseSomaMarkers.txt", header = TRUE)
mou.soma.markers <- intersect(unique(mou.markers$gene), rownames(mou.cen))
```

```{r}
genes.int <- intersect(rownames(dge.liver.dobie.cen), rownames(mou.cen))
marker.int <- intersect(rownames(dge.liver.dobie.cen), mou.soma.markers)
```

```{r}
mou.germ.liver.dobie.cor <- cor(mou.cen[genes.int,], dge.liver.dobie.cen[genes.int,], method = "spearman")
mou.germ.liver.dobie.marker.cor <- cor(mou.cen[marker.int,], dge.liver.dobie.cen[marker.int,], method = "spearman")
#saveRDS(mou.germ.liver.dobie.cor, "~/storage/Others/Tcf21/mou.germ.liver.dobie.cor.rds")
```

```{r fig.width=5, fig.height=4.5}
pdf("~/storage/Others/Tcf21/Liver_dobie.pdf", width = 5, height = 4.5)
#heart.clusters <- c("Fibroblast","Fibroblast_2","Modulated_SMC", "SMC","pericyte","Endothelial_1","Endothelial_2","Epithelial","Neuron", "Macrophage","Tcell")
Heatmap(mou.germ.liver.dobie.cor, cluster_rows = TRUE, cluster_columns = TRUE, show_row_dend = FALSE,show_column_dend = FALSE, column_title = "mouse tesits somatic vs. Liver_Dobie")
dev.off()
```

```{r fig.width=5, fig.height=4.5}
pdf("~/storage/Others/Tcf21/Liver_dobie_marker.pdf", width = 5, height = 4.5)
#heart.clusters <- c("Fibroblast","Fibroblast_2","Modulated_SMC", "SMC","pericyte","Endothelial_1","Endothelial_2","Epithelial","Neuron", "Macrophage","Tcell")
Heatmap(mou.germ.liver.dobie.marker.cor, cluster_rows = TRUE, cluster_columns = TRUE, show_row_dend = FALSE,show_column_dend = FALSE, column_title = "mouse tesits somatic vs. Liver_Dobie")
dev.off()
```


##Injured samples
```{r}
raw_3 <- readMM("~/storage/Others/Tcf21/Liver_Dobie/GSM4085625_10x_3_matrix.mtx.gz")
raw_5 <- readMM("~/storage/Others/Tcf21/Liver_Dobie/GSM4085627_10x_5_matrix.mtx.gz")
raw_3.gene <- read.table("~/storage/Others/Tcf21/Liver_Dobie/GSM4085625_10x_3_genes.tsv.gz",header = FALSE, stringsAsFactors = FALSE)
raw_3.barcode <- read.table("~/storage/Others/Tcf21/Liver_Dobie/GSM4085625_10x_3_barcodes.tsv.gz", header = FALSE, stringsAsFactors = FALSE)
raw_5.gene <- read.table("~/storage/Others/Tcf21/Liver_Dobie/GSM4085627_10x_5_genes.tsv.gz",header = FALSE, stringsAsFactors = FALSE)
raw_5.barcode <- read.table("~/storage/Others/Tcf21/Liver_Dobie/GSM4085627_10x_5_barcodes.tsv.gz", header = FALSE, stringsAsFactors = FALSE)
```

unique genes
```{r}
sum(raw_3.gene$V2!=raw_5.gene$V2) # two lists of genes are the same
genes.dup <- names(which(table(raw_3.gene$V2) >=2))
genes.unique <- raw_3.gene$V2[!raw_3.gene$V2 %in% genes.dup]
```


```{r}
liver.dobie.3 <- as.data.frame(as.matrix(raw_3))[!raw_3.gene$V2 %in% genes.dup,]
rownames(liver.dobie.3) <- genes.unique
colnames(liver.dobie.3) <- paste0("HSC_",raw_3.barcode$V1)

liver.dobie.5 <- as.data.frame(as.matrix(raw_5))[!raw_3.gene$V2 %in% genes.dup,]
rownames(liver.dobie.5) <- genes.unique
colnames(liver.dobie.5) <- paste0("PF_",raw_5.barcode$V1)
```

```{r}
liver.dobie.injured <- cbind(liver.dobie.3, liver.dobie.5)
```

```{r}
cells.genes <- apply(liver.dobie.injured,2,function(x) sum(x>0))
summary(cells.genes)
```

```{r}
dge.liver.dobie.injured <- CreateSeuratObject(raw.data = liver.dobie.injured)
dge.liver.dobie.injured <- NormalizeData(object = dge.liver.dobie.injured, normalization.method = "LogNormalize", 
    scale.factor = 10000)

dge.liver.dobie.injured <- FindVariableGenes(object = dge.liver.dobie.injured,mean.function = ExpMean, dispersion.function = LogVMR, x.low.cutoff = 0.0125, y.cutoff = 1, x.high.cutoff = 3)
dge.liver.dobie.injured <- ScaleData(object = dge.liver.dobie.injured)
dge.liver.dobie.injured <- RunPCA(object = dge.liver.dobie.injured, pc.genes = dge.liver.dobie.injured@var.genes)
```

```{r fig.width=6,fig.height=4.5}
PCAPlot(object = dge.liver.dobie.injured, dim.1 = 1, dim.2 = 2)
PCAPlot(object = dge.liver.dobie.injured, dim.1 = 1, dim.2 = 3)
PCElbowPlot(object = dge.liver.dobie.injured)
```

```{r fig.width=6,fig.height=4.5}
dge.liver.dobie.injured <- RunTSNE(object = dge.liver.dobie.injured, dims.use = 1:10)
TSNEPlot(object = dge.liver.dobie.injured)
```

```{r fig.width=6,fig.height=4.5}
dge.liver.dobie.injured <- FindClusters(object = dge.liver.dobie.injured, reduction.type = "pca", dims.use = 1:5, save.SNN = TRUE, resolution = 0.05)
DimPlot(object = dge.liver.dobie.injured, reduction = "tsne", group.by = "res.0.05",do.label = TRUE)
```

```{r fig.width=10, fig.height=10}
FeaturePlot(dge.liver.dobie.injured, features.plot = c("Tagln","Acta2","Tpm2","Gpx3","Clec3b","Cd34","Ecm1","Vipr1","Colec11"), reduction.use = "tsne",nCol = 3,pch.use = 0.1)
```

```{r}
saveRDS(dge.liver.dobie.injured, file = "~/storage/Others/Tcf21/Liver_Dobie/dge.liver.dobie.injured.rds")
dge.liver.dobie.injured <- readRDS("~/storage/Others/Tcf21/Liver_Dobie/dge.liver.dobie.injured.rds")
```


0: HSC
1: VSMC
2: FB
```{r}
dge.liver.dobie.injured@meta.data$celltypes <- plyr::mapvalues(dge.liver.dobie.injured@meta.data$res.0.05, from = c(0:2), to = c("HSC","VSMC","FB"))
```

```{r}
liver.dobie.norm <- apply(dge.liver.dobie.injured@raw.data,2,function(x) x/sum(x)*1e4)
```

```{r}
cell.types <- unique(dge.liver.dobie.injured@meta.data$celltypes)
dge.liver.dobie.injured.cen <- c()
for(i in cell.types){
  cells <- dge.liver.dobie.injured@cell.names[dge.liver.dobie.injured@meta.data$celltypes==i]
  cen <- apply(liver.dobie.norm[,cells],1,mean)
  dge.liver.dobie.injured.cen <- cbind(dge.liver.dobie.injured.cen, cen)
}
colnames(dge.liver.dobie.injured.cen) <- cell.types
```

```{r}
genes.int <- intersect(rownames(dge.liver.dobie.injured.cen), rownames(mou.cen))
marker.int <- intersect(rownames(dge.liver.dobie.injured.cen), mou.soma.markers)
```

```{r}
mou.germ.liver.dobie.inj.cor <- cor(mou.cen[genes.int,], dge.liver.dobie.injured.cen[genes.int,], method = "spearman")
mou.germ.liver.dobie.marker.inj.cor <- cor(mou.cen[marker.int,], dge.liver.dobie.injured.cen[marker.int,], method = "spearman")
#saveRDS(mou.germ.liver.dobie.cor, "~/storage/Others/Tcf21/mou.germ.liver.dobie.cor.rds")
```

```{r fig.width=5, fig.height=4.5}
pdf("~/storage/Others/Tcf21/Liver_dobie_injured.pdf", width = 5, height = 4.5)
#heart.clusters <- c("Fibroblast","Fibroblast_2","Modulated_SMC", "SMC","pericyte","Endothelial_1","Endothelial_2","Epithelial","Neuron", "Macrophage","Tcell")
Heatmap(mou.germ.liver.dobie.inj.cor, cluster_rows = TRUE, cluster_columns = TRUE, show_row_dend = FALSE,show_column_dend = FALSE, column_title = "mouse tesits somatic vs. Liver_Dobie")
dev.off()
```

```{r fig.width=5, fig.height=4.5}
pdf("~/storage/Others/Tcf21/Liver_dobie_injured_marker.pdf", width = 5, height = 4.5)
#heart.clusters <- c("Fibroblast","Fibroblast_2","Modulated_SMC", "SMC","pericyte","Endothelial_1","Endothelial_2","Epithelial","Neuron", "Macrophage","Tcell")
Heatmap(mou.germ.liver.dobie.marker.inj.cor, cluster_rows = TRUE, cluster_columns = TRUE, show_row_dend = FALSE,show_column_dend = FALSE, column_title = "mouse tesits somatic vs. Liver_Dobie")
dev.off()
```

```{r}
saveRDS(dge.liver.dobie.injured.cen, file = "~/storage/Others/Tcf21/dge.liver.dobie.injured.cen.rds")
```

